---
# handlers file for package-security-check

- name: Send notification message via Slack
  vars:
    dc_slack_message: "New docker update for {{ diff_output.path }} available!"
    dc_slack_channel: "slacknotificationtesting"
    dc_slack_username: "Docker Updates"
    dc_slack_token: "T145LBQGJ/BMUK33E2C/h2cOENxbkbYlktlbSMNFNzad"
  slack:
    token: "{{ dc_slack_token }}"
    msg: "{{ dc_slack_message }}"
    channel: '#"{{ dc_slack_channel }}"'
    username: '"{{ dc_slack_username }}"'
    parse: 'none'
  delegate_to: localhost
  when: is_different.result.rc == "1"
  listen: send_slack_notification
