---
- name: Slack message check
  fail:
    msg: "ERROR: When want to send a message to the slack you have to state at least se_slack_channel and se_slack_message."
  when:
    se_send_to_slack == "1" and (se_slack_channel == "" or se_slack_message == "")
