---
- name: Slack message check
  fail:
    msg: "ERROR: When want to send a message to the slack you have to state at least slack_channel and slack_message."
  when:
    slack_channel == "" or slack_message == ""
