---
#Import check.yml
- import_tasks: checks.yml

#Structure of the notifying messages to Slack
#Sending out the emails
- name: Send notification message via Slack
  slack:
    token: "{{ slack_token }}"
    msg: "{{ slack_message }}"
    channel: '#"{{ slack_channel }}"'
    username: '"{{ slack_username }}"'
    parse: 'none'
  delegate_to: localhost
