---
#Import check.yml
- import_tasks: checks.yml

#Structure of the notifying messages to Slack
#Sending out the emails
- name: Send notification message via Slack
  slack:
    token: 'T145LBQGJ/BMUK33E2C/h2cOENxbkbYlktlbSMNFNzad'
    msg: "{{ se_slack_message }}"
    channel: '#"{{ se_slack_channel }}"'
    username: 'Ansible notifications'
    parse: 'none'
  delegate_to: localhost
