---
# tasks file for package-security-check

- name: Inspect a single image
  shell: curl 'https://registry.hub.docker.com/v2/repositories/library/httpd/tags/'|jq '."results"[]["name"]'
  register: docker_facts_results

- name: List of docker facts
  debug:
    msg: "{{ docker_facts_results.stdout_lines }}" #"| map(attribute='stdout_lines') | list }}"

- name: Create a file with today's docker hub version list
  copy:
    content: "{{ docker_facts_results.stdout_lines }}"
    dest: templates/today_docker_version.txt

- name: Compare files
  shell: diff templates/today_docker_version.txt templates/yesterday_docker_version.txt
  failed_when: "diff_output.rc > 1" 
  register: diff_output

- debug:
    var: diff_output

- name: Copy today's versions to yesterday's state
  template:
    src: templates/today_docker_version.txt
    dest: templates/yesterday_docker_version.txt
