---
# tasks file for package-security-check

- name: Inspect a single image
  shell: curl 'https://registry.hub.docker.com/v2/repositories/library/httpd/tags/'|jq '."results"[]["name"]'
  # uri:
  #   url: https://registry.hub.docker.com/v2/repositories/library/httpd/tags/
  #   method: POST
  #   # body: "{{ lookup('name','mesos-consul.json') }}"
  #   body_format: json
  #   headers:
  #     Content-Type: "application/json"
  register: docker_facts_results

- name: List of docker facts
  debug:
    msg: "{{ docker_facts_results }}" | map(attribute='stdout_lines') | list }}"
