---
# tasks file for package-security-check

- name: Inspect a single image
  docker_image_facts:
    name: pacur/centos-7
  register: docker_facts_results

- name: List of docker facts
  debug:
    msg: "{{ docker_facts_results }}" # | map(attribute='path') | list }}"
