---
# tasks file for package-security-check

- name: Inspect a single image
  shell: curl 'https://registry.hub.docker.com/v2/repositories/library/httpd/tags/'|jq '."results"[]["name"]'
  register: docker_facts_results

- name: List of docker facts
  debug:
    msg: "{{ docker_facts_results.stdout_lines }}" #"| map(attribute='stdout_lines') | list }}"

- name: Create a file with today's docker hub version list
  copy:
    content: "{{ docker_facts_results.stdout_lines }}"
    dest: templates/today_docker_versions.txt

#####
- name: Get cksum of my First file
  stat:
    path : "templates/today_docker_versions.txt.results"
  register: myfirstfile

- name: Current SHA1
  set_fact:
    mf1sha1: "{{ myfirstfile.stat.checksum }}"

- name: Get cksum of my Second File (If needed you can jump this)
  stat:
    path : "templates/yesterday_docker_versions.txt.results"
  register: mysecondfile

- name: Current SHA1
  set_fact:
    mf2sha1: "{{ mysecondfile.stat.checksum }}"

- name: Compilation Changed
  debug:
    msg: "File Compare"
  failed_when:  mf2sha1 != mf1sha1
####

# - name: Show diferences
#   debug:
#     msg: "{{ difference.diff | map(attribute='after') | list }}"
#
# - name: Copy today's versions to yesterday's state
#   template:
#     src: templates/today_docker_versions.txt
#     dest: templates/yesterday_docker_versions.txt
