---
# tasks file for package-security-check

# - name: Creates a CRON for regular docker check everyday
#   cron:
#     name: Docker Update Check
#     hour: 4
#     minute: 15
#     user: root
#     job: ansible-playbook /etc/ansible/roles/docker-image-vulnerability-check/docker-image-vulnerability-check.yml -e "dc_image_name='library/httpd'" --vault-password-file /etc/ansible/vault_passwd
#     cron_file: ansible_docker_update_check
#
# - name: More useful example of looping over a command result
#   shell: "/usr/bin/frobnicate {{ item }}"
#   with_lines:
#     - "/usr/bin/frobnications_per_host --param {{ inventory_hostname }}"

- name: Inspect multi images
  uri:
    url: https://registry.hub.docker.com/v2/repositories/{{ item }}/tags/
    return_contents: yes
  register: url_results
  with_items:
   - "library/httpd"
   - "sonatype/nexus3"

- name: debug
  debug:
    msg: "{{ url_results.json.name[1] }}"


# with_items:
  #  - "library/httpd"
  #  - "sonatype/nexus3"

#
# - name: List of docker facts
#   debug:
#     msg: "{{ image_library/httpd_results.stdout_lines }}" #"| map(attribute='stdout_lines') | list }}"
#   with_items:
#    - "library/httpd"
#    - "sonatype/nexus3"

  #
  # - name: Create a file with today's docker hub version list
  #   copy:
  #     content: "{{ image_{{ item }}_results.stdout_lines }}"
  #     dest: templates/today_{{ item }}_version.txt
  #
  # - name: Compare files
  #   shell: diff templates/today_{{ item }}_version.txt templates/yesterday_docker_version.txt
  #   failed_when: "diff_output.rc > 1"
  #   register: diff_output
  #
  # - name: Set variable
  #   set_fact:
  #    is_dc_{{ item }}_version_different: "{{ diff_output.rc }}"
  #
  # - name: Copy today's versions to yesterday's state
  #   template:
  #     src: templates/today_{{ item }}_version.txt
  #     dest: templates/yesterday_{{ item }}_version.txt
