---
- name: install cronie package 
  yum: name=cronie state=installed
  tags: cronie

- name: enable cron(ie) service 
  service: name=crond state=started enabled=yes
  tags: cronie

- name: install yum-cron package 
  yum: name=yum-cron state=installed
  tags: yum-cron

- name: copy yum-cron.conf
  template: src=yum-cron.conf.j2 dest=/etc/yum/yum-cron.conf
  notify: restart yum-cron
  tags: yum-cron

- name: copy yum-cron-hourly.conf
  template: src=yum-cron-hourly.conf.j2 dest=/etc/yum/yum-cron-hourly.conf
  notify: restart yum-cron
  tags: yum-cron

- name: enable yum-cron service 
  service: name=yum-cron state=started enabled=yes
  tags: yum-cron

