---

- name: Email message check
  fail:
    msg: "ERROR: Message or template of the message must be defined in extra vars! eg.: se_message='Hello' or se_temp_type='new_version_mcc_installed'"
  when:
    se_temp_type == "" and se_message == ""

- name: Find out all templates
  find:
    paths: templates/
    recurse: yes
    patterns: '*'
    excludes: '*main.html'
  register: list_of_templates

# - name: Find created template
#   find:
#     paths: templates/
#     recurse: yes
#     patterns: '*{{ se_temp_type }}.html'
#     excludes: '*main.html'
#   register: is_template_available

- name: List of available templates
  debug:
    msg: "{{ list_of_templates.files | map(attribute='path') | list }}"

- name: Template name check
  fail:
    msg: "ERROR: Stated template {{ se_temp_type }}.html doesn't exist! You can see list of available templates one task above. State just a name of the template file without sufix."
  when:
    se_temp_type != "" #and is_template_available.matched == 0

- name: Recipients check
  fail:
    msg: "ERROR: At least one recipient must by defined in extra vars! eg.: se_to='devops@aura.cz'"
  when:
    se_to == ""

- name: Subject check
  fail:
    msg: "ERROR: Subject of the message must be defined in extra vars! eg.: se_subject='New version arrival!'"
  when:
    se_subject == ""
