---

- name: Message check
  fail:
    msg: "ERROR: Message or template of the message must be defined in extra vars! eg.: message='Hello' or se_temp_type='1'"
  when:
    se_temp_type == "" and se_message == ""

- name: Find created templates
  find:
    paths: templates/
    patterns: '*'
  register: se_created_templates

- name: Template check
  fail:
    msg: "ERROR: Stated template doesn't exist or it's not defined! Defined templates are: {{ se_created_templates | list }}"
  when:
    se_temp_type != "" and
    se_temp_type not in se_created_templates

- name: Recipients check
  fail:
    msg: "ERROR: At least one recipient must by defined in extra vars! eg.: se_recipients='devops@aura.cz'"
  when:
    se_recipients == ""

- name: Subject check
  fail:
    msg: "ERROR: Subject of the message must be defined in extra vars! eg.: se_subject='New version arrival!'"
  when:
    se_subject == ""
