---

- name: Message check
  fail:
    msg: "ERROR: Message or template of the message must be defined in extra vars! eg.: message='Hello' or se_temp_type='1'"
  when:
    se_temp_type == "" and se_message == ""

- name: Find created template
  find:
    paths: templates/
    patterns: '*{{ se_temp_type }}.html'
  register: find_result

- name: List out all templates
  find:
    paths: templates/
    patterns: '*'
  register: list_of_templates

- name: Template check
  fail:
    msg: "ERROR: Stated template {{ se_temp_type }}.html doesn't exist! Created templates are: "
  when:
    se_temp_type != "" and find_result.matched == 0

- name: List of templates
  debug:
    msg: {{ item.path }}
    with_items: "{{ list_of_templates.files }}"

- name: Recipients check
  fail:
    msg: "ERROR: At least one recipient must by defined in extra vars! eg.: se_recipients='devops@aura.cz'"
  when:
    se_recipients == ""

- name: Subject check
  fail:
    msg: "ERROR: Subject of the message must be defined in extra vars! eg.: se_subject='New version arrival!'"
  when:
    se_subject == ""
