---
#Import check.yml
- import_tasks: checks.yml

#In case you want to send some email template set "temp_type" on 2 in extra vars with the name of the template
#Copying template for New version of MCC installed email to the main_template which is to be sent
- name: Create an email template from {{ se_temp_type }}.html
  template:
    src: templates/{{ se_temp_type }}.html
    dest: templates/main.html
  when: se_temp_type != ""

#In case no template choosen you have to specify at least message in extra vars
#Copying extra var 'message' to the main_template which is to be send
- name: Create an email without template
  copy:
    content: "{{ se_message }}"
    dest: templates/main.html
  when: se_temp_type  == ""

#Structure of the notifying emails
#Sending out the emails
- name: "Sending notifying e-mails"
  mail:
    subject: "{{ se_subject }}"
    body: "{{ se_body }}"
    host: "{{ se_host }}"
    port: "{{ se_port }}"
    username: "{{ se_username }}"
    password: "{{ se_password }}"
    to: "{{ se_recipients | list }}"
    cc: "{{ se_cc }}"
    bcc: "{{ se_bcc }}"
    from: "{{ se_from }}"
    headers: "{{ se_headers | list }}"
    secure: "{{ se_secure }}"
    subtype: "{{ se_subtype }}"
