---
#Import check.yml
- import_tasks: checks.yml

#Copying choosen template to the main template which is to be sent
- name: Create an email template from {{ se_temp_type }}.html
  template:
    src: templates/{{ se_temp_type }}.html
    dest: templates/main.html
  when: se_temp_type != ""

#In case no template choosen you have to specify at least message in extra vars
#Copying extra var 'message' to the main_template which is to be send
- name: Create an email without template
  copy:
    content: "{{ se_message }}"
    dest: templates/main.html
  when: se_temp_type  == "" and se_send_to_slack == "1"

- name: Slack notification
  command: curl -X POST -H "Content-type: application/json" --data '{"text":"{{ se_message }}"}' https://hooks.slack.com/services/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
  when: se_send_to_slack == 1

#Structure of the notifying emails
#Sending out the emails
- name: "Sending notifying e-mails"
  mail:
    subject: "{{ se_subject }}"
    body: "{{ se_body }}"
    host: "{{ se_host }}"
    port: "{{ se_port }}"
    username: "{{ se_username }}"
    password: "{{ se_password }}"
    to: "{{ se_to }}"
    # cc: "{{ se_cc }}" #uncomment and specify in extra vars if you want to cc anybody
    # bcc: "{{ se_bcc }}" #uncomment and specify in extra vars if you want to bcc anybody
    from: "{{ se_from }}"
    headers: "{{ se_headers }}"
    secure: "{{ se_secure }}"
    subtype: "{{ se_subtype }}"
